### ISSUE TITLE
[Bug] Incompatible with Name Pain mod

### ISSUE THREAD

**Issue by QwertRvg** [Pedro270707/dynamic-name-tags#1]
Forge 1.20.1
Mod version 1.0.0

The mod doesn't work when installed alongside Name Pain.
Name Pain changes the colour of Name Tags and Player Names when damaged.
But, even when mobs are at full health this mod doesn't activate.

Also I think that the rainbow colour of jeb_ is more important than the damage.
And wouldn't it be possible for Dinnerbone to be the wrong way but still change colour based off damage?

**Comment by Pedro270707** [comment]
Name Pain has ARR and is closed source, so I don't think I can do anything about it. You can ask the creator of that mod to add compatibility to Dynamic Name Tags.

**Comment by QwertRvg** [comment]
Will do, thanks!
